/**
 * Notification Types
 */
const NOTIFICATION_TYPES = {
  CASE_CREATED: "CASE_CREATED",
  CASE_ASSIGNED: "CASE_ASSIGNED",
  CASE_UPDATED: "CASE_UPDATED",
  CASE_STATUS_CHANGED: "CASE_STATUS_CHANGED",
  PERSON_FOUND: "PERSON_FOUND",
  PERSON_MATCHED: "PERSON_MATCHED",
  SEARCH_ASSIGNED: "SEARCH_ASSIGNED",
  SEARCH_UPDATED: "SEARCH_UPDATED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  SYSTEM: "SYSTEM",
};

/**
 * Notification Priorities
 */
const NOTIFICATION_PRIORITIES = {
  LOW: "LOW",
  NORMAL: "NORMAL",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

/**
 * Bulk Notification Target Types
 */
const BULK_TARGET_TYPES = {
  ALL: "ALL",
  USERS: "USERS",
  ROLE: "ROLE",
};

const VALID_NOTIFICATION_TYPES = Object.values(NOTIFICATION_TYPES);
const VALID_NOTIFICATION_PRIORITIES = Object.values(NOTIFICATION_PRIORITIES);
const VALID_BULK_TARGET_TYPES = Object.values(BULK_TARGET_TYPES);

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITIES,
  BULK_TARGET_TYPES,
  VALID_NOTIFICATION_TYPES,
  VALID_NOTIFICATION_PRIORITIES,
  VALID_BULK_TARGET_TYPES,
};